[NO-TASK] added asset endpoint
LOCKbusiness/api pull request #253
Opened 2023-02-08 18:14 UTC by Krysh90

2023-02-08 23:23 UTC, davidleomay commented on src/shared/models/asset/asset.controller.ts
> +@ApiTags('asset')
`@ApiTags('Asset')`

2023-02-08 23:23 UTC, davidleomay commented on src/shared/models/asset/asset.controller.ts
> +  }
If the AuthGuard is set, then jwt is never undefined.

2023-02-08 23:23 UTC, davidleomay commented on src/shared/models/asset/asset.dto.ts
> +  category: AssetCategory;
Haha, good descriptions 😆

2023-02-08 23:23 UTC, davidleomay commented on src/shared/models/asset/asset.controller.ts
> +  }
In LOCK we started creating separate mapper classes, e.g. _src/subdomains/staking/application/mappers/withdrawal-output-dto.mapper.ts_

2023-02-08 23:23 UTC, davidleomay commented on src/shared/models/asset/asset.controller.ts
> +  }
I think we should add buyable/sellable columns to the entity, to be able to disable some assets.

2023-02-09 07:45 UTC, Krysh90 commented on src/shared/models/asset/asset.dto.ts
> +  category: AssetCategory;
open for any suggestion :D

2023-02-09 11:23 UTC, davidleomay requested changes

2023-02-09 11:23 UTC, davidleomay commented on migration/1675928633077-asset-buyable-sellable.js
> +    }
Remove all database references (`"sqldb-lock-api-dev".`)

2023-02-09 12:33 UTC, davidleomay approved these changes

2023-02-09 12:39 UTC, merged